### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by PalomitasTime** [CharlieWhile13/commcenterpatch13#1] opened 2020-08-15 03:22 UTC
Just git clone and make package, got this errors:

> Making all for tweak CCPatch13…
==> Preprocessing Tweak.x…
==> Compiling Tweak.x (arm64)…
Tweak.x:2:46: error: expected ')'
__unused static int (*_logos_orig$_ungrouped$"__Z50VerifyCarrierBundleVersionsXMLSignatureWithKeyTypePK14__CFDictionary16C...
                                             ^
Tweak.x:2:21: note: to match this '('
__unused static int (*_logos_orig$_ungrouped$"__Z50VerifyCarrierBundleVersionsXMLSignatureWithKeyTypePK14__CFDictionary16C...
                    ^
Tweak.x:2:226: error: expected ';' after top level declarator
  ...__unused static int _logos_function$_ungrouped$"__Z50VerifyCarrierBundleVersionsXMLSignatureWithKeyTypePK14__CFDictionary1...
                                                    ^
                                                    ;
Tweak.x:7:116: error: expected ';' after top level declarator
  ...static int (*_logos_orig$_ungrouped$"_SecKeyRawVerify")(); __unused static int _logos_function$_ungrouped$"_SecKeyRawVerif...
                                                                                                               ^
                                                                                                               ;
Tweak.x:11:232: error: expected ';' after top level declarator
  ...__unused static int _logos_function$_ungrouped$"__Z28VerifyCarrierBundleSignatureRKNSt3__112basic_stringIcNS_11char_traits...
                                                    ^
                                                    ;
Tweak.x:15:197: error: expected ';' after top level declarator
  ...__unused static int _logos_function$_ungrouped$"__Z39VerifyCarrierBundleVersionsXMLSignaturePK14__CFDictionary16CBVersions...
                                                    ^
                                                    ;
Tweak.x:20:207: error: expected ';' after top level declarator
  ...__unused static int _logos_function$_ungrouped$"__Z28VerifyCarrierBundleSignatureRKNSt3__112basic_stringIcNS_11char_traits...
                                                    ^
                                                    ;
6 errors generated.
make[3]: *** [/Users/palomitas/Desktop/commcenterpatch13/.theos/obj/debug/arm64/Tweak.x.00d2de2a.o] Error 1
make[2]: *** [/Users/palomitas/Desktop/commcenterpatch13/.theos/obj/debug/arm64/CCPatch13.dylib] Error 2
make[1]: *** [internal-library-all_] Error 2
make: *** [CCPatch13.all.tweak.variables] Error 2

**Comment by elihwyma** [comment] 2020-08-15 13:23
Yep, I've been able to re-produce this issue, and it looks like it might of been caused by a Theos update changing how I need to do it, I'll look into it

**Comment by elihwyma** [comment] 2020-08-20 21:59
This should now be fixed on latest commit

**Closed as completed** 2020-08-21 13:25 UTC
